-- Sigma DataTech Silver Layer Fix Queries
-- Generated by CrewAI DQ Crew | 2026-05-29T17:55:59.942579

-- FIX: duplicate transaction check | SEVERITY: HIGH | RISK: LOW
UPDATE silver_transactions SET quality_flag='REVIEW' WHERE transaction_id IS NOT NULL AND amount >= 0;
-- ROLLBACK: restore quality_flag from backup table