"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T12:28:19.134617+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession, Window
from pyspark.sql.functions import broadcast, col, current_timestamp, input_file_name, lit, row_number, when
from pyspark.sql.types import DateType, FloatType, StringType


def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    transactions = spark.read.option("header", True).csv(input_path)
    bronze = (
        transactions
        .withColumn("transaction_id", col("transaction_id").cast(StringType()))
        .withColumn("ingestion_timestamp", current_timestamp())
        .withColumn("source_file", input_file_name())
        .withColumn("pipeline_run_id", lit(run_id))
        .withColumn("date", lit(run_date))
    )
    bronze.write.mode("append").partitionBy("date").parquet(output_path)
    return bronze


def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    bronze = spark.read.parquet(bronze_path).filter(col("date") == run_date)
    merchants = spark.read.parquet(merchants_path).cache()
    typed = (
        bronze
        .withColumn("amount", col("amount").cast(FloatType()))
        .withColumn("transaction_date", col("transaction_date").cast(DateType()))
        .withColumn("transaction_id", col("transaction_id").cast(StringType()))
        .withColumn("merchant_id", col("merchant_id").cast(StringType()))
        .withColumn("customer_id", col("customer_id").cast(StringType()))
    )
    filtered = typed.filter(col("transaction_id").isNotNull()).filter(col("amount") >= 0)
    window = Window.partitionBy("transaction_id").orderBy(col("ingestion_timestamp").desc())
    deduped = filtered.withColumn("rn", row_number().over(window)).filter(col("rn") == 1).drop("rn")
    silver = (
        deduped
        .join(broadcast(merchants), "merchant_id", "left")
        .withColumn("quality_flag", when(col("merchant_name").isNull(), "UNMATCHED").otherwise("CLEAN"))
    )
    silver.write.mode("append").partitionBy("date").parquet(output_path)
    return silver


def main():
    spark = SparkSession.builder.appName("SigmaTransactionPipeline").getOrCreate()
    run_date = "2024-01-15"
    run_id = "manual-run"
    ingest_bronze(spark, "data/transactions.csv", "data/bronze", run_date, run_id)
    transform_silver(spark, "data/bronze", "data/merchants", "data/silver", run_date)

# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql.functions import avg, col, count, countDistinct, first, last, sum as spark_sum, when


def build_merchant_performance(spark, silver_path, output_path, run_date):
    silver = spark.read.parquet(silver_path).filter(col("date") == run_date)
    result = silver.groupBy("merchant_id", "merchant_name", "category", "city", "date").agg(
        spark_sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
        count("*").alias("txn_count"),
        (spark_sum(when(col("status") == "FAILED", 1).otherwise(0)) / count("*") * 100).alias("failure_rate_pct"),
    )
    result.write.mode("append").partitionBy("date").parquet(f"{output_path}/merchant_performance")
    return result


def build_customer_ltv(spark, silver_path, output_path):
    silver = spark.read.parquet(silver_path)
    completed = silver.filter(col("status") == "COMPLETED")
    result = completed.groupBy("customer_id").agg(
        spark_sum("amount").alias("total_spent"),
        count("*").alias("total_txns"),
        avg("amount").alias("avg_txn_value"),
        first("transaction_date").alias("first_txn_date"),
        last("transaction_date").alias("last_txn_date"),
        first("payment_method").alias("preferred_payment_method"),
    )
    result.write.mode("overwrite").parquet(f"{output_path}/customer_ltv")
    return result


def build_daily_summary(spark, silver_path, output_path, run_date):
    silver = spark.read.parquet(silver_path).filter(col("date") == run_date)
    result = silver.groupBy("date").agg(
        spark_sum(when(col("status") == "COMPLETED", col("amount")).otherwise(0)).alias("total_revenue"),
        count("*").alias("total_txns"),
        countDistinct("customer_id").alias("unique_customers"),
        countDistinct("merchant_id").alias("unique_merchants"),
        (spark_sum(when(col("status") == "FAILED", 1).otherwise(0)) / count("*") * 100).alias("failure_rate_pct"),
    )
    result.write.mode("append").partitionBy("date").parquet(f"{output_path}/daily_summary")
    return result


def run_gold(spark, silver_path, gold_output_dir, run_date):
    merchant = build_merchant_performance(spark, silver_path, gold_output_dir, run_date)
    customer = build_customer_ltv(spark, silver_path, gold_output_dir)
    daily = build_daily_summary(spark, silver_path, gold_output_dir, run_date)
    run_metadata = {"run_date": run_date, "tables": 3, "status": "SUCCESS"}
    return {"merchant": merchant, "customer": customer, "daily": daily, "metadata": run_metadata}